name: Publish docker image

on:
  release:
    types: [published]
  push:
    branches:
      - master         # Push events on master branch

jobs:
  deploy-docker:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - base: "devito:nvidia"
            tag: 'nvidia-nvc'

          - base: "devito:nvidia-clang"
            tag: 'nvidia-clang'

          - base: "python:3.7"
            tag: "cpu"

    steps:
      - name: Checkout devito
        uses: actions/checkout@v3

      - name: Check event name
        run: echo ${{ github.event_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ matrix.image }}
          tags: |
            type=ref,event=pr,value=${{ matrix.tag }}-dev
            type=semver,event=tag,value=${{ matrix.tag }}-{{version}}
            type=semver,event=tag,value=${{ matrix.tag }}-latest
            type=raw,value=latest,enable=${{ matrix.base == "python:3.7"}}
            # Legacy "gpu" tag
            type=ref,event=pr,value=gpu-dev,enable=${{ matrix.base == "devito:nvidia"}}
            type=semver,event=tag,value=gpu-{{version}}
            type=semver,event=tag,value=gpu-latest

      - name: Build and push image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: base=${{ matrix.base }}

  test-image:
    needs: deploy-docker
    runs-on: ${{ matrix.runner }}

    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: "devito:nvidia-nvc-dev"
            flag: '--gpus all'
            runner: [self-hosted, gpu, docker]
            test: 'tests/test_gpu_opeacc.py'

          - tag: 'nvidia-clang-dev'
            runner: [self-hosted, gpu, docker]
            flag: '--gpus all'
            test: 'tests/test_gpu_openmp.py'

          - tag: "cpu-dev"
            runner:  ubuntu-latest
            flag: '--gpus all'
            test: 'tests/test_operator.py'
  
    steps:
        - name: Run simple test
          run: |
             docker pull 'devitocodes/devito:${{ matrix.im-name }}'
             docker run ${{ matrix.flag }} --rm --name testrun 'devitocodes/devito:${{ matrix.tag }}' pytest ${{ matrix.test }}
