name: Publish devito docker images from compiler bases

on:
  release:
    types: [published]
  push:
    branches:
      - master         # Push events on master branch

jobs:
  deploy-devito:
    runs-on: ${{ matrix.runner }}
    env:
      # Use buildkit https://docs.docker.com/develop/develop-images/build_enhancements/ for better build
      DOCKER_BUILDKIT: "1"

    strategy:
      fail-fast: false
      matrix:
        include:
          - base: "bases:nvidia-nvc"
            tag: 'nvidia-nvc'
            flag: '--gpus all'
            test: 'tests/test_gpu_openacc.py tests/test_gpu_common.py'
            runner: ["self-hosted", "gpu", "docker"]

          - base: "bases:nvidia-clang"
            tag: 'nvidia-clang'
            flag: '--gpus all'
            test: 'tests/test_gpu_openmp.py tests/test_gpu_common.py'
            runner: ["self-hosted", "gpu", "docker"]

          # Runtime gpu flags from https://hub.docker.com/r/rocm/tensorflow/
          - base: "bases:amd"
            tag: 'amd'
            flag: '--network=host --device=/dev/kfd --device=/dev/dri --ipc=host --group-add video'
            test: 'tests/test_gpu_openmp.py'
            runner: ["self-hosted", "gpu", "docker", "aomp"]

          - base: "bases:cpu-gcc"
            tag: "gcc"
            flag: ''
            test: 'tests/test_operator.py'
            runner: ubuntu-latest

          - base: "bases:cpu-icc"
            tag: "icc"
            flag: ''
            test: 'tests/test_operator.py'
            runner: ubuntu-latest

    steps:
      - name: Checkout devito
        uses: actions/checkout@v3

      - name: Check event name
        run: echo ${{ github.event_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: |
            ${{ matrix.image }}
          # Create all the tags to be pushed
          # event is the trigger even (pr for pull request, tag for release)
          # value is the tag
          # enable is a "if" filter
          tags: |
            type=ref,event=pr,value=${{ matrix.tag }}-dev
            type=semver,event=tag,value=${{ matrix.tag }}-{{version}}
            type=semver,event=tag,value=${{ matrix.tag }}-latest
            type=raw,value=latest,enable=${{ matrix.base == "python:3.7"}}
            # Legacy "gpu" tag
            type=ref,event=pr,value=gpu-dev,enable=${{ matrix.base == "bases:nvidia-nvc"}}
            type=semver,event=tag,value=gpu-{{version}}
            type=semver,event=tag,value=gpu-latest
            # Legacy "cpu" tag
            type=ref,event=pr,value=cpu-dev,enable=${{ matrix.base == "bases:cpu-gcc"}}
            type=semver,event=tag,value=cpu-{{version}}
            type=semver,event=tag,value=cpu-latest

      - name: Build and push image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile.devito
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          build-args: base=devitocodes/${{ matrix.base }}

      - name: Run tests
        run: |
         docker run ${{ matrix.flag }} --rm --name testrun 'devitocodes/devito:${{ matrix.tag }}-dev' pytest ${{ matrix.test }}
