name: Build base docker images

# Runs once a week for now.
on:
  workflow_dispatch:
    # Allow to run by hand
  schedule:
    - cron: "0 13 * * 1"

jobs:
  deploy-docker-nvidia:
    if: inputs.image != 'clang' 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout devito
        uses: actions/checkout@v3

      - name: Check event name
        run: echo ${{ github.event_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: NVIDIA image
        if: github.event_name == 'push'
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile.nvidia
          push: true
          tags: devitocodes/devito:nvidia


  deploy-docker-clang:
      runs-on: ubuntu-latest
      needs: deploy-docker-nvidia

      steps:
        - name: Checkout devito
          uses: actions/checkout@v3

        - name: Check event name
          run: echo ${{ github.event_name }}

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Clang image
          if: github.event_name == 'push'
          uses: docker/build-push-action@v3
          with:
            context: .
            file: ./docker/Dockerfile.nvidia.clang
            push: true
            tags: devitocodes/devito:nvidia-clang