name: Build base compilers docker images

on:
  push:
    branches:
      - docker-with-bases
  workflow_dispatch:
    # Allow to run by hand
  schedule:
    # Run once a week
    - cron: "0 13 * * 1"

jobs:
  deploy-docker-bases:
    name: ${{ matrix.tag }}
    runs-on: ${{ matrix.runner }}
    env:
      DOCKER_BUILDKIT: "1"

    strategy:
      fail-fast: false
      matrix:
        include:
          - tag: 'devitocodes/bases:nvidia-nvc'
            arch: 'arch=nvc'
            version: ''
            dockerfile: './docker/Dockerfile.nvidia'
            runner: ["self-hosted", "gpu", "openacc"]

          - tag: 'devitocodes/bases:nvidia-clang'
            arch: 'arch=clang'
            version: 'ver=nvhpc-21-11'
            dockerfile: './docker/Dockerfile.nvidia'
            runner: ["self-hosted", "gpu", "openmp", "clang"]

          # That one is tiny run on default
          - tag: 'devitocodes/bases:cpu-gcc'
            arch: ''
            version: ''
            dockerfile: './docker/Dockerfile.cpu'
            runner: ubuntu-latest 

          - tag: 'devitocodes/bases:amd'
            arch: ''
            version: ''
            dockerfile: './docker/Dockerfile.amd'
            runner: ["self-hosted", "gpu", "docker", "aomp"]

    steps:
      - name: Checkout devito
        uses: actions/checkout@v3

      - name: Check event name
        run: echo ${{ github.event_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          build-args: |
            ${{ matrix.arch }}
            ${{ matrix.version }}
          tags: ${{ matrix.tag }}
