name: Build base compilers docker images

# Runs once a week for now.
on:
  workflow_dispatch:
    # Allow to run by hand
  schedule:
    - cron: "0 13 * * 1"

jobs:
  deploy-base-nvidia:
    runs-on:  [self-hosted, gpu, docker]
    strategy:
      fail-fast: false
      matrix:
        inculde:
          - tag: ''
            build-arg: ''

          - tag: '21-11'
            build-arg: 'ver=nvhpc-21-11'
    
   steps:
      - name: Checkout devito
        uses: actions/checkout@v3

      - name: Check event name
        run: echo ${{ github.event_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: NVIDIA image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./docker/Dockerfile.nvidia
          push: true
          build-arg: ${{ matrix.build-arg }}
          tags: devitocodes/devito:nvidia-${{ matrix.tag }}


  deploy-base-nvidia-clang:
      runs-on:  [self-hosted, gpu, docker]
      needs: deploy-docker-nvidia

      steps:
        - name: Checkout devito
          uses: actions/checkout@v3

        - name: Check event name
          run: echo ${{ github.event_name }}

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        - name: Clang image
          uses: docker/build-push-action@v3
          with:
            context: .
            file: ./docker/Dockerfile.nvidia.clang
            push: true
            tags: devitocodes/devito:nvidia-clang
