name: Build base compilers docker images

on:
  push:
    paths:
      - '/docker/Dockerfile.nvidia'
      - '/docker/Dockerfile.cpu'
      - '/docker/Dockerfile.amd'
  workflow_dispatch:
    inputs:
      tags:
        description: 'Build compiler bases'
  schedule:
    # Run once a week
    - cron: "0 13 * * 1"

jobs:
#######################################################
################### CPU ###############################
#######################################################
  deploy-cpu-bases:
    name: ${{ matrix.tag }}
    runs-on: ${{ matrix.runner }}
    env:
      DOCKER_BUILDKIT: "1"

    steps:
      - name: Checkout devito
        uses: actions/checkout@v3

      - name: Check event name
        run: echo ${{ github.event_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: cleanup
        run: docker system prune -a -f

      - name: Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: './docker/Dockerfile.cpu'
          push: true
          build-args: |
            'arch=gcc'
          tags: 'devitocodes/bases:cpu-gcc'

      - name: Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: './docker/Dockerfile.cpu'
          push: true
          build-args: |
            'arch=icx'
          tags: 'devitocodes/bases:cpu-icx'

      - name: Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: './docker/Dockerfile.cpu'
          push: true
          build-args: |
            'arch=icc'
          tags: 'devitocodes/bases:cpu-icc'

#######################################################
################### Nvidia nvhpc ######################
#######################################################
  deploy-nvidia-bases:
    name: "nvidia-bases"
    runs-on: ["self-hosted", "nvidiagpu"]
    env:
      DOCKER_BUILDKIT: "1"

    steps:
      - name: Checkout devito
        uses: actions/checkout@v3

      - name: Check event name
        run: echo ${{ github.event_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: cleanup
        run: docker system prune -a -f

      - name: Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: './docker/Dockerfile.nvidia'
          push: true
          build-args: |
            'arch=nvc'
          tags: 'devitocodes/bases:nvidia-nvc'

      - name: Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: './docker/Dockerfile.nvidia'
          push: true
          build-args: |
            'arch=nvcc'
          tags: 'devitocodes/bases:nvidia-nvcc'

      - name: Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: './docker/Dockerfile.nvidia'
          push: true
          build-args: |
            'arch=nvc-host'
          tags: 'devitocodes/bases:cpu-nvc'

#######################################################
################### Nvidia clang ######################
# # clang is only officialy supporting cuda<11.5. The latest nvidia sdk with cuda 11.5 is 21.11 (last of 2021)
# # We cannot use newer ones such as 22-1 because the package manager automatically installs the latest 2022
# # that re-install the latest (11.7) version on top of it.
# # For more info check https://llvm.org/docs/CompileCudaWithLLVM.html and the Prerequisites 
#######################################################
  deploy-nvidia-clang-base:
    name: "nvidia-clang-base"
    runs-on: ["self-hosted", "nvidiagpu"]
    env:
      DOCKER_BUILDKIT: "1"

    steps:
      - name: Checkout devito
        uses: actions/checkout@v3

      - name: Check event name
        run: echo ${{ github.event_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: cleanup
        run: docker system prune -a -f

      - name: Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: './docker/Dockerfile.nvidia'
          push: true
          build-args: |
            'arch=clang'
            'ver=nvhpc-21-11'
          tags: 'devitocodes/bases:nvidia-clang'

#######################################################
##################### AMD #############################
#######################################################
  deploy-amd-bases:
    name: "amd-base"
    runs-on: ["self-hosted", "amdgpu"]
    env:
      DOCKER_BUILDKIT: "1"

    steps:
      - name: Checkout devito
        uses: actions/checkout@v3

      - name: Check event name
        run: echo ${{ github.event_name }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: cleanup
        run: docker system prune -a -f

      - name: Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: './docker/Dockerfile.amd'
          push: true
          tags: devitocodes/bases:amd

      - name: Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: './docker/Dockerfile.amd'
          push: true
          build-args: |
            arch=hip
          tags: devitocodes/bases:amd-hip