# Runner information:
# OpenACC on NVidia runs on `sarlaac`
# OpenMP on NVidia runs on `kimogila`
# OpenMP on AMD runs on `wampa`

name: CI-gpu

env:
  OUTPUT_PATH: ${{ github.workspace }}
  RESOURCE_GROUP: CI-gpu

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Push-button activation
  workflow_dispatch:
    inputs:
      tags:
        description: 'Run GPU tests'

jobs:

  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.tags }}

    env:
      DEVITO_ARCH: ${{ matrix.arch }}
      DEVITO_PLATFORM: ${{ matrix.platform }}
      DEVITO_LANGUAGE: ${{ matrix.language }}
      OMPI_CC: ${{ matrix.arch }}

    strategy:
      # Prevent all builds from terminating if one fails
      fail-fast: false

      matrix:
        name: [
          pytest-gpu-omp-nvidia,
          pytest-gpu-acc-nvidia,
          pytest-gpu-omp-amd
        ]
        include:
        - name: pytest-gpu-omp-nvidia
          test_file: "tests/test_gpu_openmp.py"
          base: "devitocodes/devito:nvidia-clang"
          tags: ["self-hosted", "gpu", "openmp", "clang"]

        - name: pytest-gpu-acc-nvidia
          test_file: "tests/test_gpu_openacc.py"
          base: "devitocodes/devito:nvidia-nvc"
          tags: ["self-hosted", "gpu", "openacc"]

        - name: pytest-gpu-omp-amd
          test_file: "tests/test_gpu_openmp.py"
          tags: ["self-hosted", "gpu", "openmp", "aomp"]
          base: "devitocodes/devito:amd-aomp"

    steps:
    - name: Checkout devito
      uses: actions/checkout@v3

    - name: Build docker image
      run: |
          docker build . --file docker/Dockerfile.devito --tag devito_img --build-arg base=${{ matrix.base }}

    - name: Test with pytest
      run: |
        docker run --gpus all --rm --name testrun devito_img pytest --cov --cov-config=.coveragerc --cov-report=xml tests/test_adjoint.py tests/test_gpu_common.py ${{ matrix.test_file }}

    - name: Test examples
      run: |
        docker run --gpus all --rm --name testrun devito_img pytest examples/seismic/acoustic/acoustic_example.py
        docker run --gpus all --rm --name testrun devito_img pytest examples/seismic/elastic/elastic_example.py
        docker run --gpus all --rm --name testrun devito_img pytest examples/seismic/tti/tti_example.py
        docker run --gpus all --rm --name testrun devito_img pytest examples/seismic/viscoacoustic/viscoacoustic_example.py
        docker run --gpus all --rm --name testrun devito_img pytest examples/seismic/viscoelastic/viscoelastic_example.py

    - name: Test examples with MPI
      run: |
        docker run --gpus all --rm --name testrun --env DEVITO_MPI=1 devito_img mpirun -n 2 pytest examples/seismic/acoustic/acoustic_example.py
        docker run --gpus all --rm --name testrun --env DEVITO_MPI=1 devito_img mpirun -n 2 pytest examples/seismic/elastic/elastic_example.py
        docker run --gpus all --rm --name testrun --env DEVITO_MPI=1 devito_img mpirun -n 2 pytest examples/seismic/tti/tti_example.py
        docker run --gpus all --rm --name testrun --env DEVITO_MPI=1 devito_img mpirun -n 2 pytest examples/seismic/viscoacoustic/viscoacoustic_example.py
        docker run --gpus all --rm --name testrun --env DEVITO_MPI=1 devito_img mpirun -n 2 pytest examples/seismic/viscoelastic/viscoelastic_example.py

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: ${{ matrix.name }}
