# Runner information:
# TODO: Summarize runner hardware for each config here

name: CI-gpu

env:
  OUTPUT_PATH: ${{ github.workspace }}
  RESOURCE_GROUP: CI-gpu

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  # Push-button activation
  workflow_dispatch:
    inputs:
      tags:
        description: 'Run GPU tests'

jobs:

  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.tags }}

    env:
      DEVITO_ARCH: ${{ matrix.arch }}
      DEVITO_PLATFORM: ${{ matrix.platform }}
      DEVITO_LANGUAGE: ${{ matrix.language }}
      OMPI_CC: ${{ matrix.arch }}

    strategy:
      # Prevent all build from terminating if one fails
      fail-fast: false

      matrix:
        name: [
          # NOTE: We can re-instate this as a 'failing' build
          # as soon as the hardware is ready
          #pytest-gpu-omp,
          pytest-gpu-acc,
          pytest-gpu-aomp
        ]
        include:
        #- name: pytest-gpu-omp
          #test_file: "tests/test_gpu_openmp.py"
          #arch: "clang"
          #platform: "nvidiaX"
          #language: "openmp"
          #tags: ["self-hosted", "gpu", "openmp"]

        - name: pytest-gpu-acc
          test_file: "tests/test_gpu_openacc.py"
          arch: "pgcc"
          platform: "nvidiaX"
          language: "openacc"
          tags: ["self-hosted", "gpu", "openacc"]

        - name: pytest-gpu-aomp
          test_file: "TODO"
          arch: "TODO"
          platform: "TODO"
          language: "TODO"
          tags: ["self-hosted", "gpu", "aomp"]

    steps:
    - name: Checkout devito
      uses: actions/checkout@v1

    # TODO: Below needs fixing. Suggest creating suitable matrix
    # entries to load appropriate paths etc. from local files.
    # See asv.yml for an example. Note that there may now be a nice action
    # available for doing this so that would be worth looking into.
    - name: Set VIRTUAL_ENV
      run: |
        echo "VIRTUAL_ENV=$ENVHOME/something" >> $GITHUB_ENV
        echo "PATH=$VIRTUAL_ENV/bin:$PATH" >> $GITHUB_ENV

    # NOTE: Depending on above step is modified this may or may not
    # need changing
    - name: Set PATH
      run: |
        echo "PATH=$VIRTUAL_ENV/bin:$PATH" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        pip3 install --upgrade pip
        pip3 install -e .[extras]

    - name: Test with pytest
      run: |
        # NOTE: Maybe we want to change the below to print
        # output of nvidia-smi and amd equivalent on each machine?
        # It's simply to ensure gpu driver has not broken
        if [ "${{ matrix.name }}" == 'pytest-gpu-acc' ]; then
          pgaccelinfo
        fi
        pytest --cov --cov-config=.coveragerc --cov-report=xml tests/test_gpu_common.py
        pytest --cov --cov-config=.coveragerc --cov-report=xml ${{ matrix.test_file }}

    - name: Test examples
      run: |
        pytest examples/seismic/acoustic/acoustic_example.py
        pytest examples/seismic/elastic/elastic_example.py
        pytest examples/seismic/tti/tti_example.py
        pytest examples/seismic/viscoacoustic/viscoacoustic_example.py
        pytest examples/seismic/viscoelastic/viscoelastic_example.py

    - name: Test examples with MPI
      run: |
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/acoustic/acoustic_example.py
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/elastic/elastic_example.py
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/tti/tti_example.py
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoacoustic/viscoacoustic_example.py
        DEVITO_MPI=1 mpirun -n 2 pytest examples/seismic/viscoelastic/viscoelastic_example.py

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1.0.6
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        name: ${{ matrix.name }}
